# Site settings
author: Mark Harvey
title: Harvey Flatiron Work
header-img: img/home-bg.png
email: maharvey2@crimson.ua.edu
copyright_name: Mark Harvey
description: > # this means to ignore newlines until "baseurl:"
  A blog for the work found in Flatiron 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  maharvey2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
